version: '3'
services:
  jenkins:
    container_name: jenkins_flopes
    image: myjenkins/maven
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
  sonarqube:
    container_name: sonarqube_flopes
    image: sonarqube:lts
    ports:
      - 9000:9000
    volumes:
      - $PWD/sonarqube_home/conf:/opt/sonarqube/conf
      - $PWD/sonarqube_home/data:/opt/sonarqube/data
      - $PWD/sonarqube_home/logs:/opt/sonarqube/logs
      - $PWD/sonarqube_home/extensions:/opt/sonarqube/extensions
    networks:
      - net
networks:
  net:
