version: '3'
services:
  jenkins:
    container_name: jenkins_flopes
    image: myjenkins/maven
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
  sonarqube:
    container_name: sonarqube_flopes
    image: sonarqube:lts
    ports:
      - 9000:9000
    volumes:
      - $PWD/sonarqube_home/conf:/opt/sonarqube/conf
      - $PWD/sonarqube_home/data:/opt/sonarqube/data
      - $PWD/sonarqube_home/logs:/opt/sonarqube/logs
      - $PWD/sonarqube_home/extensions:/opt/sonarqube/extensions
    networks:
      - net
  tomcat:
    container_name: tomcat_flopes
    image: my/tomcat
    ports:
      - "8081:8080"
    volumes:
      - $PWD/tomcat_home/webapps:/usr/local/tomcat/webapps
#      - $PWD/tomcat_home/conf:/usr/local/tomcat/conf
    networks:
     - net  
networks:
  net:
